[tool.poetry]
name = "memecry"
version = "0.1.0"
description = ""
authors = ["crpier <crpier42@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.20.0"
python-multipart = "^0.0.5"
aiofiles = "^22.1.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
babel = "^2.11.0"
gunicorn = "^20.1.0"
sqlite-fts4 = "^1.0.3"
types-pillow = "^9.5.0.4"
types-aiofiles = "^23.1.0.2"
types-python-jose = "^3.3.4.7"
types-passlib = "^1.7.7.12"
starlette = "^0.31.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.20"}
aiosqlite = "^0.19.0"
pydantic = {extras = ["email"], version = "^2.4.2"}
pydantic-settings = "^2.0.3"
relax-py = "^0.1.0"


[tool.poetry.group.dev.dependencies]
isort = "^5.11.4"
black = "^22.12.0"
mypy = "^1.2.0"
ruff = "^0.0.265"
pydeps = "^1.12.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
