[tool.poetry]
name = "memecry"
version = "0.1.0"
description = ""
authors = ["crpier <crpier42@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
uvicorn = "^0.20.0"
python-multipart = "^0.0.5"
aiofiles = "^22.1.0"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
sqlmodel = "^0.0.8"
pydantic = {extras = ["dotenv", "email"], version = "^1.10.4"}
jinja2 = "^3.1.2"
babel = "^2.11.0"
gunicorn = "^20.1.0"
simple-html = "^0.7.0"
opencv-python = "^4.7.0.72"
pillow = "^9.5.0"
pytesseract = "^0.3.10"
numpy = "^1.24.3"
matplotlib = "^3.7.1"
sqlite-fts4 = "^1.0.3"
types-pillow = "^9.5.0.4"
types-aiofiles = "^23.1.0.2"
types-python-jose = "^3.3.4.7"
types-passlib = "^1.7.7.12"
starlette = "^0.31.0"
hypercorn = "^0.14.4"


[tool.poetry.group.dev.dependencies]
isort = "^5.11.4"
black = "^22.12.0"
mypy = "^1.2.0"
ruff = "^0.0.265"
pydeps = "^1.12.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
